INSERT INTO CATEGORIES (category_name, status) VALUES ('MEYVE, SEBZE', 0);
INSERT INTO CATEGORIES (category_name, status) VALUES ('ATIŞTIRMALIK', 0);
INSERT INTO CATEGORIES (category_name, status) VALUES ('TEMEL GIDA', 0);
INSERT INTO CATEGORIES (category_name, status) VALUES ('SUT VE SUT URUNLERI', 0);

INSERT INTO AMOUNT_TYPES (TYPE, status) VALUES ('Litre', 0);
INSERT INTO AMOUNT_TYPES (TYPE, status) VALUES ('Kilogram', 0);
INSERT INTO AMOUNT_TYPES (TYPE, status) VALUES ('Adet', 0);

INSERT INTO PRODUCTS (PRODUCT_NAME, UNIT_PRICE, AMOUNTTYPE_ID, CATEGORY_ID, status) VALUES ('PORTAKAL', 22.99, 2, 1, 0);
INSERT INTO PRODUCTS (PRODUCT_NAME, UNIT_PRICE, AMOUNTTYPE_ID, CATEGORY_ID, status) VALUES ('PATLICAN', 10.45, 2, 1, 0);

INSERT INTO PRODUCTS (PRODUCT_NAME, UNIT_PRICE, AMOUNTTYPE_ID, CATEGORY_ID, status) VALUES ('ÜLKER ÇİKOLATALI GOFRET', 1.45, 3, 2, 0);
INSERT INTO PRODUCTS (PRODUCT_NAME, UNIT_PRICE, AMOUNTTYPE_ID, CATEGORY_ID, status) VALUES ('ETİ CANGA', 2.25, 3, 2, 0);

INSERT INTO PRODUCTS (PRODUCT_NAME, UNIT_PRICE, AMOUNTTYPE_ID, CATEGORY_ID, status) VALUES ('CARREFOUR JASMINE PIRINC', 14.90, 2, 3, 0);
INSERT INTO PRODUCTS (PRODUCT_NAME, UNIT_PRICE, AMOUNTTYPE_ID, CATEGORY_ID, status) VALUES ('REIS KOFTELIK BULGUR', 11.50, 2, 3, 0);

INSERT INTO PRODUCTS (PRODUCT_NAME, UNIT_PRICE, AMOUNTTYPE_ID, CATEGORY_ID, status) VALUES ('CARREFOUR YAĞLI SÜT', 5.25, 1, 4, 0);
INSERT INTO PRODUCTS (PRODUCT_NAME, UNIT_PRICE, AMOUNTTYPE_ID, CATEGORY_ID, status) VALUES ('CARREFOUR YARIM YAĞLI SÜT', 4.90, 1, 4, 0);

UPDATE CATEGORIES
SET CATEGORY_NAME = 'BAKLİYAT'
WHERE CATEGORY_ID = 3



SELECT * FROM AMOUNT_TYPES;
SELECT * FROM CATEGORIES;
SELECT * FROM PRODUCTS;